  
const CSV_HEADERS = [
  { id: 'id', title: 'Job ID' },
  { id: 'date_posted', title: 'Date Posted' },
  { id: 'date_created', title: 'Date Created' },
  { id: 'title', title: 'Job Title' },
  { id: 'organization', title: 'Company' },
  { id: 'organization_url', title: 'Company URL' },
  { id: 'date_validthrough', title: 'Valid Through' },
  { id: 'location_type', title: 'Location Type' },
  { id: 'salary_raw', title: 'Salary' },
  { id: 'employment_type', title: 'Employment Type' },
  { id: 'url', title: 'Job URL' },
  { id: 'source_type', title: 'Source Type' },
  { id: 'source', title: 'Source' },
  { id: 'source_domain', title: 'Source Domain' },
  { id: 'organization_logo', title: 'Company Logo' },
  { id: 'cities_derived', title: 'Cities' },
  { id: 'regions_derived', title: 'Regions' },
  { id: 'countries_derived', title: 'Countries' },
  { id: 'locations_derived', title: 'Locations' },
  { id: 'timezones_derived', title: 'Timezones' },
  { id: 'lats_derived', title: 'Latitudes' },
  { id: 'lngs_derived', title: 'Longitudes' },
  { id: 'remote_derived', title: 'Remote' },
  { id: 'recruiter_name', title: 'Recruiter Name' },
  { id: 'recruiter_title', title: 'Recruiter Title' },
  { id: 'recruiter_url', title: 'Recruiter URL' },
  { id: 'linkedin_org_employees', title: 'Company Employees' },
  { id: 'linkedin_org_url', title: 'LinkedIn Company URL' },
  { id: 'linkedin_org_size', title: 'Company Size' },
  { id: 'linkedin_org_slogan', title: 'Company Slogan' },
  { id: 'linkedin_org_industry', title: 'Industry' },
  { id: 'linkedin_org_followers', title: 'Company Followers' },
  { id: 'linkedin_org_headquarters', title: 'Company HQ' },
  { id: 'linkedin_org_type', title: 'Company Type' },
  { id: 'linkedin_org_foundeddate', title: 'Company Founded' },
  { id: 'linkedin_org_specialties', title: 'Company Specialties' },
  { id: 'linkedin_org_locations', title: 'Company Locations' },
  { id: 'linkedin_org_description', title: 'Company Description' },
  { id: 'linkedin_org_recruitment_agency_derived', title: 'Recruitment Agency' },
  { id: 'seniority', title: 'Seniority Level' },
  { id: 'directapply', title: 'Direct Apply' },
  { id: 'linkedin_org_slug', title: 'Company Slug' },
  { id: 'no_jb_schema', title: 'No JB Schema' },
  { id: 'external_apply_url', title: 'External Apply URL' },
  { id: 'description_text', title: 'Job Description' },
  { id: 'locations_raw', title: 'Raw Locations' },
  { id: 'location_requirements_raw', title: 'Location Requirements' }
];

module.exports = CSV_HEADERS;
